# Cleaning Data — Real Estate Dataset
**Data Science Course — Python Data Playbook Submission Assignment**

This notebook walks through common data cleaning steps on the Real Estate dataset:
normalizing a column, renaming/dropping columns, removing duplicates, and filling missing values.

In [1]:
import pandas as pd

# Load the Real Estate CSV into a DataFrame
data = pd.read_csv('Realestate.csv')

In [2]:
# --- NORMALIZE houseAge using Min-Max Scaling ---
# Formula: (value - min) / (max - min)
# This scales all values to a 0-1 range so they are comparable
min_age = data['houseAge'].min()   # 0.0
max_age = data['houseAge'].max()   # 43.8

data['houseAgeStandardized'] = (data['houseAge'] - min_age) / (max_age - min_age)

In [3]:
# --- DROP the numberOfConvenienceStores column ---
# inplace=True makes the change persist directly on the DataFrame
data.drop(columns=['numberOfConvenienceStores'], inplace=True)

In [4]:
# --- RENAME the transaction column to transactionDate ---
# Clearer column names improve readability and reduce confusion
data.rename(columns={'transaction': 'transactionDate'}, inplace=True)

In [5]:
# --- USE .loc[] TO DISPLAY ROWS 0 THROUGH 10 ---
# .loc[] is label-based — both endpoints are INCLUSIVE
# This returns 11 rows (0, 1, 2 ... 10)
data.loc[0:10]

,No,transactionDate,houseAge,distanceToNearestMRTstation,latitude,longitude,housePriceOfUnitArea,houseAgeStandardized
0,1,2012.917,32.0,84.87882,24.98298,121.54024,NaN,0.730594
1,2,2012.917,19.5,306.59470,24.98034,121.53951,42.2,0.445205
2,3,2013.583,13.3,561.98450,24.98746,121.54391,47.3,0.303653
3,4,2013.500,13.3,561.98450,24.98746,121.54391,54.8,0.303653
4,5,2012.833,5.0,390.56840,24.97937,121.54245,43.1,0.114155
5,6,2012.667,7.1,2175.03000,24.96305,121.51254,32.1,0.162100
6,7,2012.667,34.5,623.47310,24.97933,121.53642,40.3,0.787671
7,8,2013.417,20.3,287.60250,24.98042,121.54228,46.7,0.463470
8,9,2013.500,31.7,5512.03800,24.95095,121.48458,18.8,0.723744
9,10,2013.417,17.9,1783.18000,24.96731,121.51486,22.1,0.408676
10,11,2013.083,34.8,405.21340,24.97349,121.53372,41.4,0.794521

In [6]:
# --- USE .iloc[] TO DISPLAY THE FIRST 10 ROWS ---
# .iloc[] is position-based — end index is EXCLUSIVE
# iloc[0:10] returns rows at positions 0-9 (10 rows total)
data.iloc[0:10]

,No,transactionDate,houseAge,distanceToNearestMRTstation,latitude,longitude,housePriceOfUnitArea,houseAgeStandardized
0,1,2012.917,32.0,84.87882,24.98298,121.54024,NaN,0.730594
1,2,2012.917,19.5,306.59470,24.98034,121.53951,42.2,0.445205
2,3,2013.583,13.3,561.98450,24.98746,121.54391,47.3,0.303653
3,4,2013.500,13.3,561.98450,24.98746,121.54391,54.8,0.303653
4,5,2012.833,5.0,390.56840,24.97937,121.54245,43.1,0.114155
5,6,2012.667,7.1,2175.03000,24.96305,121.51254,32.1,0.162100
6,7,2012.667,34.5,623.47310,24.97933,121.53642,40.3,0.787671
7,8,2013.417,20.3,287.60250,24.98042,121.54228,46.7,0.463470
8,9,2013.500,31.7,5512.03800,24.95095,121.48458,18.8,0.723744
9,10,2013.417,17.9,1783.18000,24.96731,121.51486,22.1,0.408676

In [7]:
# --- FIND AND REMOVE DUPLICATE ROWS ---
# duplicated() returns True for every row that is an exact copy of a previous row
# drop_duplicates() removes those rows; inplace=True applies the change to the dataset
print("Duplicate rows found:", data.duplicated().sum())
print("Rows before removing duplicates:", len(data))

data.drop_duplicates(inplace=True)

print("Rows after removing duplicates: ", len(data))

Duplicate rows found: 4
Rows before removing duplicates: 418
Rows after removing duplicates:  414

In [8]:
# --- FIND MISSING VALUES AND FILL WITH THE MEAN ---
# isnull().sum() counts NaN values in each column
print("Missing values per column:")
print(data.isnull().sum().to_string())

# Fill missing numeric values with the column mean so no data is lost
print("\nFilling missing housePriceOfUnitArea values with the column mean...")
data['housePriceOfUnitArea'] = data['housePriceOfUnitArea'].fillna(data['housePriceOfUnitArea'].mean())

print("Missing values remaining after fill:", data.isnull().sum().sum())

Missing values per column:
No                             0
transactionDate                0
houseAge                       0
distanceToNearestMRTstation    0
latitude                       0
longitude                      0
housePriceOfUnitArea           3
houseAgeStandardized           0

Filling missing housePriceOfUnitArea values with the column mean...
Missing values remaining after fill: 0